language: go

os:
  - osx
  - windows
  - linux

go:
  - 1.14.x
  - 1.15.x

go_import_path: github.com/thinkgos/TODO_ADD_PACKAGENAME

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go";
    export PATH="$GOPATH/bin:$PATH"; fi
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

install:
  - go get -u golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - go get -v ./...
  - |-
    case $TRAVIS_OS_NAME in
      linux|osx)
        golint ./... | reviewdog -f=golint -reporter=github-check
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-check
        golint ./... | reviewdog -f=golint -reporter=github-pr-review
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-pr-review
        ;;
    esac
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash >
    .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash);
    fi

env:
  global:
    - GO111MODULE=on
    - secure: HvVP8vz7vsDDQZ19gYvYM+LBnPDE/LuOeLeuVWuuYljlqN9Xppz4OP9nml4VG+j5V2jYlsmNlKpcGr+dL0vPVkuI3gB0NLMNzPawBAslG5GZ46u920CVRL1StlBOu9UmF3yi4atwzY/E90Vi49o4uS730aNYrA9iUGJD69q59GLmToHgGtGSRyXl9HQp+mXXgs6JARs3V1h++e6ZQe2bylhe5rSYfaSsXE7S1lR9Iq3xmqSNCF05X4xfqhhxzf2734PkKeEKF/8JdB5MpUOlPiQ6399jOSLRG5mcL5Z1GJhThz0aSW5r1GYporXaarJm8RBx6HGOGlZ6TZFUHMXgI0yZnlkmmpn4RW5bHo+9MJZy3X1rq+VYPa97kLYCQb6pXcEyf0QMRMosvoZurdNSE30J9QsOzPuwiJ9tjTsk1L9Ca9GjJ44yg054ZRHsfLlfwUSCS0BsTyOocZNSf0YsIvsU+1DbXD7ohPzcHGujB2324BuI3hNojFaf2wNhzrbfg1dOmNH6Y9+WvEzwJpKwaNna7xq0N3Bx3wKcb1BBNmIL4AXk8sfhVEK7aa+mV0Os0DL7D7yz5RypYTUDTB7l9I3FlvhYk2UJ67w3ksMTBJkld+EtzdgQpH2NS4VjSqKnUCSY8HstL0OoroKzgJ+L3ZE6rxFirmZdBzxpJnoq3DY=